version: "3.5"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    user: "node"
    working_dir: /home/node/app
    command: "yarn run start"
    networks:
      - frontend
      - backend

  # See https://hub.docker.com/_/postgres for details on using
  # the postgres docker container.
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_DB: ftyp
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - ftyp-data:/var/lib/postgresql/data
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/data:/ftyp/data
      - ./db/scripts:/ftyp/scripts
    networks:
      - backend
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    command: "serve -s build"
    volumes:
      - ./client:/home/node/app
    networks:
      - frontend

networks:
  frontend:
  backend:

volumes:
  ftyp-data: {}
