version: "3.5"
services:
  proxy:
    image: nginx:mainline-alpine
    ports:
      - "${PROXY_PORT:-8888}:80"
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d
    networks:
      - frontend
  api:
    build:
      context: ./api
    image: flybase/ftyp-api:${TAG:-latest}
    restart: "on-failure"
    environment:
      FTYP_API_MODE: public
      PGHOST: db
      PGDATABASE: ${FTYP_PGDATABASE:?Set the FTYP database name}
      PGPASSWORD: ${FTYP_PUBLIC_PASSWORD:?Set the dedicated public API password}
    networks:
      - frontend
      - internal
  api-admin:
    image: flybase/ftyp-api:${TAG:-latest}
    restart: "on-failure"
    environment:
      FTYP_API_MODE: admin
      PGHOST: db
      PGDATABASE: ${FTYP_PGDATABASE:?Set the FTYP database name}
      PGPASSWORD: ${FTYP_ADMIN_PASSWORD:?Set the dedicated admin API password}
    networks:
      - frontend
      - internal

  # See https://hub.docker.com/_/postgres for details on using
  # the postgres docker container.
  db:
    # Uncomment image line below in production.
    image: flybase/ftyp-db:${TAG:-latest}
    # Uncomment build context for development
    #build:
    #  context: ./db
    restart: always
    environment:
      POSTGRES_DB: ${FTYP_PGDATABASE:-ftyp}
      POSTGRES_PASSWORD: ${FTYP_PGPASSWORD:?Set the database owner password}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - ftyp-data:/var/lib/postgresql/data
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/data:/ftyp/data
      - ./db/scripts:/ftyp/scripts
    networks:
      - internal
  client:
    image: flybase/ftyp-client:${TAG:-latest}
    working_dir: "/home/node/app"
    command: "serve -s build -l 5000"
    volumes:
      - ./client:/home/node/app
    networks:
      - frontend

networks:
  frontend:
  internal:

volumes:
  ftyp-data: {}

