query PubQuery($terms: String) {
  pubs: searchPubs(terms: $terms, first: 1000) {
    totalCount
    nodes {
      uniquename
      miniref
      title
      curationStatus
      hasSubmission
      type {
        name
      }
    }
  }
}
